/*
 * waysome - wayland based window manager
 *
 * Copyright in alphabetical order:
 *
 * Copyright (C) 2014-2015 Julian Ganz
 * Copyright (C) 2014-2015 Manuel Messner
 * Copyright (C) 2014-2015 Marcel Müller
 * Copyright (C) 2014-2015 Matthias Beyer
 * Copyright (C) 2014-2015 Nadja Sommerfeld
 *
 * This file is part of waysome.
 *
 * waysome is free software: you can redistribute it and/or modify it under the
 * terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation, either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * waysome is distributed in the hope that it will be useful, but WITHOUT ANY
 * WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
 * A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with waysome. If not, see <http://www.gnu.org/licenses/>.
 */

#include <errno.h>
#include <stddef.h>

#include "action/manager.h"
#include "action/processor.h"
#include "action/processor_stack.h"
#include "objects/message/error_reply.h"
#include "objects/message/transaction.h"
#include "objects/message/value_reply.h"
#include "objects/set.h"
#include "objects/string.h"
#include "util/condition.h"

/**
 * Event-transaction mapping
 *
 * Helper type for mapping a name of a event to the transactions for the event.
 */
struct evt_mapping {
    /**
     * Name of the event
     *
     * @warning This member _MUST_ be the first member of the struct.
     *
     * This member is the first member of the struct because the ws_set_get
     * function casts this type to `struct ws_object*` when doing `ws_set_get()`
     * and finds the string then. Then it does the compare stuff with the string
     * objects (and their compare callbacks). This gives us the possibility to
     * pass a `struct ws_string` object to `ws_set_get()` and we do not have to
     * (stack-)allocate a `struct evt_mapping` for a comparison. We also do not
     * have to make it a `struct ws_object` subtype this way.
     */
    struct ws_string ev_name;
    struct ws_set transactions; //!< Set holding the transactions
};

/**
 * Internal context type
 */
struct actman_ctx {
    struct ws_set event_transaction_mappings; //!< event-transaction mapping
};

/*
 * Variable for holding the internal context
 */
static struct actman_ctx ctx;

/*
 *
 * Forward declarations
 *
 */

/**
 * Run a transaction
 *
 * This function will run a transaction and generate a reply by returning either
 * an error reply message or a value reply message transporting the topmost
 * element from the processor stack, if the transaction left anything, tat is.
 * If the transaction didn't leave a value, a nil value will be embedded in the
 * reply.
 *
 * @return reply generated by running the transaction
 */
static struct ws_reply*
run_transaction(
    struct ws_transaction* transaction // transaction to run
);

/**
 * Register a transaction for an event
 *
 * Register a transaction for an event by name. The `name` parameter can be
 * free()'d afterwards, it is put into the mapping by
 * `ws_string_set_from_str()`, so no need to keep the `name` parameter. The `t`
 * is put directly into the set of the mappings and shouldn't be free()'d.
 */
int
register_transaction_on_event_by_name(
    struct ws_string* name, //!< The name of the event
    struct ws_transaction* t //!< The transaction to register
);

/*
 *
 * Interface implementation
 *
 */

int
ws_action_manager_init(void)
{
    static bool done = false;
    if (done) {
        return 0;
    }

    if (ws_set_init(&ctx.event_transaction_mappings) != 0) {
        return -ENOMEM;
    }

    done = true;
    return 0;
}

int
ws_action_manager_deinit(void)
{
    bool r;
    r = ws_object_deinit((struct ws_object*) &ctx.event_transaction_mappings);

    if (r) {
        return 0;
    }
    return -1;
}

struct ws_reply*
ws_action_manager_process(
    struct ws_message* message
) {
    // check whether the message is a transaction
    if (message->obj.id == &WS_OBJECT_TYPE_ID_TRANSACTION) {
        struct ws_transaction* transaction;
        transaction = (struct ws_transaction*) message;

        // get the flags
        enum ws_transaction_flags flags = ws_transaction_flags(transaction);

        //!< @todo store the transaction if requested

        if (flags & WS_TRANSACTION_FLAGS_EXEC) {
            // execute the transaction
            return run_transaction(transaction);
        }

        return NULL;
    }

    //!< @todo handle event messages

    return NULL;
}


/*
 *
 * Internal implementation
 *
 */

static struct ws_reply*
run_transaction(
    struct ws_transaction* transaction // transaction to run
) {
    struct ws_reply* retval = NULL;
    int res;

    // prepare the stack
    struct ws_processor_stack stack;
    res = ws_processor_stack_init(&stack);
    if (res < 0) {
        retval = (struct ws_reply*)
                 ws_error_reply_new(transaction, -res, "Could not init stack",
                                    NULL);
        goto cleanup_stack;
    }

    //!< @todo push environment on the stack

    // we start a new frame, but we will never restore the default frame
    (void) ws_processor_stack_start_frame(&stack);

    // get the commands from the transaction
    struct ws_transaction_command_list* commands;
    commands = ws_transaction_commands(transaction);
    if (!commands) {
        retval = (struct ws_reply*)
                 ws_error_reply_new(transaction, EINVAL,
                                    "Command list malformed", NULL);
        goto cleanup_stack;
    }

    // prepare the processor
    struct ws_processor proc;
    res = ws_processor_init(&proc, &stack, commands);
    if (res < 0) {
        retval = (struct ws_reply*)
                 ws_error_reply_new(transaction, -res,
                                    "Could not init processor", NULL);
        goto cleanup_stack;
    }

    // run processor
    res = ws_processor_exec(&proc);
    if (res < 0) {
        //!< @todo more elaborate error description
        retval = (struct ws_reply*)
                 ws_error_reply_new(transaction, -res,
                                    "Could not exec transaction", NULL);
        goto cleanup_processor;
    }

    // create the return message from the transaction and the value
    struct ws_value* value = ws_processor_stack_value_at(&stack, -1, NULL);
    retval = (struct ws_reply*) ws_value_reply_new(transaction, value);

    // cleanup

cleanup_processor:
    ws_processor_deinit(&proc);

cleanup_stack:
    ws_processor_stack_deinit(&stack);
    return retval;
}

int
register_transaction_on_event_by_name(
    struct ws_string* name,
    struct ws_transaction* t
) {
    struct ws_object* map = NULL;

    map = ws_set_get(&ctx.event_transaction_mappings,
                     (struct ws_object*) name);

    if (!map) {
        // There is no mapping yet, we must create one

        struct evt_mapping* tmp = calloc(1, sizeof(*tmp));
        if (unlikely(!tmp)) {
            return -ENOMEM;
        }

        int ret = ws_set_init(&tmp->transactions);
        if (unlikely(ret != 0)) {
            goto err_new_map_tmp;
        }

        ret = ws_string_set_from_str(&tmp->ev_name, name);
        if (unlikely(ret != 0)) {
            goto err_new_map;
        }

        ret = ws_set_insert(&tmp->transactions, (struct ws_object*) t);
        if (unlikely(ret != 0)) {
            goto err_new_map;
        }

        return 0;

err_new_map:
        ws_object_deinit((struct ws_object*) &tmp->transactions);
err_new_map_tmp:
        free(tmp);
        return ret;
    }

    struct evt_mapping* evt = (struct evt_mapping*) map; // cast

    return ws_set_insert(&evt->transactions, (struct ws_object*) t);
}
